// Generated by gencpp from file niryo_robot_arm_commander/GetFKResponse.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_ARM_COMMANDER_MESSAGE_GETFKRESPONSE_H
#define NIRYO_ROBOT_ARM_COMMANDER_MESSAGE_GETFKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <niryo_robot_msgs/RobotState.h>

namespace niryo_robot_arm_commander
{
template <class ContainerAllocator>
struct GetFKResponse_
{
  typedef GetFKResponse_<ContainerAllocator> Type;

  GetFKResponse_()
    : pose()  {
    }
  GetFKResponse_(const ContainerAllocator& _alloc)
    : pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::niryo_robot_msgs::RobotState_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::niryo_robot_arm_commander::GetFKResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_arm_commander::GetFKResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetFKResponse_

typedef ::niryo_robot_arm_commander::GetFKResponse_<std::allocator<void> > GetFKResponse;

typedef boost::shared_ptr< ::niryo_robot_arm_commander::GetFKResponse > GetFKResponsePtr;
typedef boost::shared_ptr< ::niryo_robot_arm_commander::GetFKResponse const> GetFKResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_arm_commander::GetFKResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_arm_commander::GetFKResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace niryo_robot_arm_commander

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'niryo_robot_arm_commander': ['/home/niryo/catkin_ws/src/niryo_robot_arm_commander/msg', '/home/niryo/catkin_ws/devel/share/niryo_robot_arm_commander/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'niryo_robot_msgs': ['/home/niryo/catkin_ws/src/niryo_robot_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_arm_commander::GetFKResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_arm_commander::GetFKResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_arm_commander::GetFKResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_arm_commander::GetFKResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_arm_commander::GetFKResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_arm_commander::GetFKResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_arm_commander::GetFKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1c262742eda7688d62d102f5b236cf47";
  }

  static const char* value(const ::niryo_robot_arm_commander::GetFKResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1c262742eda7688dULL;
  static const uint64_t static_value2 = 0x62d102f5b236cf47ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_arm_commander::GetFKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_arm_commander/GetFKResponse";
  }

  static const char* value(const ::niryo_robot_arm_commander::GetFKResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_arm_commander::GetFKResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_msgs/RobotState pose\n\
\n\
\n\
================================================================================\n\
MSG: niryo_robot_msgs/RobotState\n\
geometry_msgs/Point position\n\
niryo_robot_msgs/RPY rpy\n\
geometry_msgs/Quaternion orientation\n\
\n\
geometry_msgs/Twist twist\n\
float64 tcp_speed\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: niryo_robot_msgs/RPY\n\
# roll, pitch and yaw\n\
\n\
float64 roll\n\
float64 pitch\n\
float64 yaw\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::niryo_robot_arm_commander::GetFKResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_arm_commander::GetFKResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetFKResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_arm_commander::GetFKResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_arm_commander::GetFKResponse_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::niryo_robot_msgs::RobotState_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_ARM_COMMANDER_MESSAGE_GETFKRESPONSE_H
