// Generated by gencpp from file niryo_robot_arm_commander/GetJointLimitsResponse.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_ARM_COMMANDER_MESSAGE_GETJOINTLIMITSRESPONSE_H
#define NIRYO_ROBOT_ARM_COMMANDER_MESSAGE_GETJOINTLIMITSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <niryo_robot_arm_commander/JointLimits.h>

namespace niryo_robot_arm_commander
{
template <class ContainerAllocator>
struct GetJointLimitsResponse_
{
  typedef GetJointLimitsResponse_<ContainerAllocator> Type;

  GetJointLimitsResponse_()
    : joint_limits()  {
    }
  GetJointLimitsResponse_(const ContainerAllocator& _alloc)
    : joint_limits(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::niryo_robot_arm_commander::JointLimits_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::niryo_robot_arm_commander::JointLimits_<ContainerAllocator> >::other >  _joint_limits_type;
  _joint_limits_type joint_limits;





  typedef boost::shared_ptr< ::niryo_robot_arm_commander::GetJointLimitsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_arm_commander::GetJointLimitsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetJointLimitsResponse_

typedef ::niryo_robot_arm_commander::GetJointLimitsResponse_<std::allocator<void> > GetJointLimitsResponse;

typedef boost::shared_ptr< ::niryo_robot_arm_commander::GetJointLimitsResponse > GetJointLimitsResponsePtr;
typedef boost::shared_ptr< ::niryo_robot_arm_commander::GetJointLimitsResponse const> GetJointLimitsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_arm_commander::GetJointLimitsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_arm_commander::GetJointLimitsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace niryo_robot_arm_commander

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'niryo_robot_arm_commander': ['/home/niryo/catkin_ws/src/niryo_robot_arm_commander/msg', '/home/niryo/catkin_ws/devel/share/niryo_robot_arm_commander/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'niryo_robot_msgs': ['/home/niryo/catkin_ws/src/niryo_robot_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_arm_commander::GetJointLimitsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_arm_commander::GetJointLimitsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_arm_commander::GetJointLimitsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_arm_commander::GetJointLimitsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_arm_commander::GetJointLimitsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_arm_commander::GetJointLimitsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_arm_commander::GetJointLimitsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ba7b9bef3b3cda7f3761fd7553bd662";
  }

  static const char* value(const ::niryo_robot_arm_commander::GetJointLimitsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ba7b9bef3b3cda7ULL;
  static const uint64_t static_value2 = 0xf3761fd7553bd662ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_arm_commander::GetJointLimitsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_arm_commander/GetJointLimitsResponse";
  }

  static const char* value(const ::niryo_robot_arm_commander::GetJointLimitsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_arm_commander::GetJointLimitsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_arm_commander/JointLimits[] joint_limits\n\
\n\
================================================================================\n\
MSG: niryo_robot_arm_commander/JointLimits\n\
string name\n\
float64 min\n\
float64 max\n\
";
  }

  static const char* value(const ::niryo_robot_arm_commander::GetJointLimitsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_arm_commander::GetJointLimitsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_limits);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetJointLimitsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_arm_commander::GetJointLimitsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_arm_commander::GetJointLimitsResponse_<ContainerAllocator>& v)
  {
    s << indent << "joint_limits[]" << std::endl;
    for (size_t i = 0; i < v.joint_limits.size(); ++i)
    {
      s << indent << "  joint_limits[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::niryo_robot_arm_commander::JointLimits_<ContainerAllocator> >::stream(s, indent + "    ", v.joint_limits[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_ARM_COMMANDER_MESSAGE_GETJOINTLIMITSRESPONSE_H
