// Generated by gencpp from file niryo_robot_arm_commander/JointLimits.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_ARM_COMMANDER_MESSAGE_JOINTLIMITS_H
#define NIRYO_ROBOT_ARM_COMMANDER_MESSAGE_JOINTLIMITS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_robot_arm_commander
{
template <class ContainerAllocator>
struct JointLimits_
{
  typedef JointLimits_<ContainerAllocator> Type;

  JointLimits_()
    : name()
    , min(0.0)
    , max(0.0)  {
    }
  JointLimits_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , min(0.0)
    , max(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef double _min_type;
  _min_type min;

   typedef double _max_type;
  _max_type max;





  typedef boost::shared_ptr< ::niryo_robot_arm_commander::JointLimits_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_arm_commander::JointLimits_<ContainerAllocator> const> ConstPtr;

}; // struct JointLimits_

typedef ::niryo_robot_arm_commander::JointLimits_<std::allocator<void> > JointLimits;

typedef boost::shared_ptr< ::niryo_robot_arm_commander::JointLimits > JointLimitsPtr;
typedef boost::shared_ptr< ::niryo_robot_arm_commander::JointLimits const> JointLimitsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_arm_commander::JointLimits_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_arm_commander::JointLimits_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace niryo_robot_arm_commander

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'niryo_robot_arm_commander': ['/home/niryo/catkin_ws/src/niryo_robot_arm_commander/msg', '/home/niryo/catkin_ws/devel/share/niryo_robot_arm_commander/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'niryo_robot_msgs': ['/home/niryo/catkin_ws/src/niryo_robot_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_arm_commander::JointLimits_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_arm_commander::JointLimits_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_arm_commander::JointLimits_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_arm_commander::JointLimits_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_arm_commander::JointLimits_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_arm_commander::JointLimits_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_arm_commander::JointLimits_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef2fdc304582ee66b1e713dcd141f286";
  }

  static const char* value(const ::niryo_robot_arm_commander::JointLimits_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef2fdc304582ee66ULL;
  static const uint64_t static_value2 = 0xb1e713dcd141f286ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_arm_commander::JointLimits_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_arm_commander/JointLimits";
  }

  static const char* value(const ::niryo_robot_arm_commander::JointLimits_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_arm_commander::JointLimits_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
float64 min\n\
float64 max\n\
";
  }

  static const char* value(const ::niryo_robot_arm_commander::JointLimits_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_arm_commander::JointLimits_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.min);
      stream.next(m.max);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointLimits_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_arm_commander::JointLimits_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_arm_commander::JointLimits_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "min: ";
    Printer<double>::stream(s, indent + "  ", v.min);
    s << indent << "max: ";
    Printer<double>::stream(s, indent + "  ", v.max);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_ARM_COMMANDER_MESSAGE_JOINTLIMITS_H
