// Generated by gencpp from file niryo_robot_arm_commander/ShiftPose.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_ARM_COMMANDER_MESSAGE_SHIFTPOSE_H
#define NIRYO_ROBOT_ARM_COMMANDER_MESSAGE_SHIFTPOSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_robot_arm_commander
{
template <class ContainerAllocator>
struct ShiftPose_
{
  typedef ShiftPose_<ContainerAllocator> Type;

  ShiftPose_()
    : axis_number(0)
    , value(0.0)  {
    }
  ShiftPose_(const ContainerAllocator& _alloc)
    : axis_number(0)
    , value(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _axis_number_type;
  _axis_number_type axis_number;

   typedef double _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::niryo_robot_arm_commander::ShiftPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_arm_commander::ShiftPose_<ContainerAllocator> const> ConstPtr;

}; // struct ShiftPose_

typedef ::niryo_robot_arm_commander::ShiftPose_<std::allocator<void> > ShiftPose;

typedef boost::shared_ptr< ::niryo_robot_arm_commander::ShiftPose > ShiftPosePtr;
typedef boost::shared_ptr< ::niryo_robot_arm_commander::ShiftPose const> ShiftPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_arm_commander::ShiftPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_arm_commander::ShiftPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace niryo_robot_arm_commander

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'niryo_robot_arm_commander': ['/home/niryo/catkin_ws/src/niryo_robot_arm_commander/msg', '/home/niryo/catkin_ws/devel/share/niryo_robot_arm_commander/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'niryo_robot_msgs': ['/home/niryo/catkin_ws/src/niryo_robot_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_arm_commander::ShiftPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_arm_commander::ShiftPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_arm_commander::ShiftPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_arm_commander::ShiftPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_arm_commander::ShiftPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_arm_commander::ShiftPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_arm_commander::ShiftPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1582f6063ca2d2749f4798d853f452ac";
  }

  static const char* value(const ::niryo_robot_arm_commander::ShiftPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1582f6063ca2d274ULL;
  static const uint64_t static_value2 = 0x9f4798d853f452acULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_arm_commander::ShiftPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_arm_commander/ShiftPose";
  }

  static const char* value(const ::niryo_robot_arm_commander::ShiftPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_arm_commander::ShiftPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 axis_number\n\
float64 value\n\
";
  }

  static const char* value(const ::niryo_robot_arm_commander::ShiftPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_arm_commander::ShiftPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.axis_number);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShiftPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_arm_commander::ShiftPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_arm_commander::ShiftPose_<ContainerAllocator>& v)
  {
    s << indent << "axis_number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.axis_number);
    s << indent << "value: ";
    Printer<double>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_ARM_COMMANDER_MESSAGE_SHIFTPOSE_H
