// Generated by gencpp from file niryo_robot_rpi/DigitalIOState.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_RPI_MESSAGE_DIGITALIOSTATE_H
#define NIRYO_ROBOT_RPI_MESSAGE_DIGITALIOSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <niryo_robot_rpi/DigitalIO.h>
#include <niryo_robot_rpi/DigitalIO.h>

namespace niryo_robot_rpi
{
template <class ContainerAllocator>
struct DigitalIOState_
{
  typedef DigitalIOState_<ContainerAllocator> Type;

  DigitalIOState_()
    : digital_inputs()
    , digital_outputs()  {
    }
  DigitalIOState_(const ContainerAllocator& _alloc)
    : digital_inputs(_alloc)
    , digital_outputs(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::niryo_robot_rpi::DigitalIO_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::niryo_robot_rpi::DigitalIO_<ContainerAllocator> >::other >  _digital_inputs_type;
  _digital_inputs_type digital_inputs;

   typedef std::vector< ::niryo_robot_rpi::DigitalIO_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::niryo_robot_rpi::DigitalIO_<ContainerAllocator> >::other >  _digital_outputs_type;
  _digital_outputs_type digital_outputs;





  typedef boost::shared_ptr< ::niryo_robot_rpi::DigitalIOState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_rpi::DigitalIOState_<ContainerAllocator> const> ConstPtr;

}; // struct DigitalIOState_

typedef ::niryo_robot_rpi::DigitalIOState_<std::allocator<void> > DigitalIOState;

typedef boost::shared_ptr< ::niryo_robot_rpi::DigitalIOState > DigitalIOStatePtr;
typedef boost::shared_ptr< ::niryo_robot_rpi::DigitalIOState const> DigitalIOStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_rpi::DigitalIOState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_rpi::DigitalIOState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace niryo_robot_rpi

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'niryo_robot_msgs': ['/home/niryo/catkin_ws/src/niryo_robot_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'niryo_robot_rpi': ['/home/niryo/catkin_ws/src/niryo_robot_rpi/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_rpi::DigitalIOState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_rpi::DigitalIOState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_rpi::DigitalIOState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_rpi::DigitalIOState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_rpi::DigitalIOState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_rpi::DigitalIOState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_rpi::DigitalIOState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e3301c19a16019595490fc28259868bd";
  }

  static const char* value(const ::niryo_robot_rpi::DigitalIOState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe3301c19a1601959ULL;
  static const uint64_t static_value2 = 0x5490fc28259868bdULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_rpi::DigitalIOState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_rpi/DigitalIOState";
  }

  static const char* value(const ::niryo_robot_rpi::DigitalIOState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_rpi::DigitalIOState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_rpi/DigitalIO[] digital_inputs\n\
niryo_robot_rpi/DigitalIO[] digital_outputs\n\
================================================================================\n\
MSG: niryo_robot_rpi/DigitalIO\n\
string name\n\
bool value\n\
";
  }

  static const char* value(const ::niryo_robot_rpi::DigitalIOState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_rpi::DigitalIOState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.digital_inputs);
      stream.next(m.digital_outputs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DigitalIOState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_rpi::DigitalIOState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_rpi::DigitalIOState_<ContainerAllocator>& v)
  {
    s << indent << "digital_inputs[]" << std::endl;
    for (size_t i = 0; i < v.digital_inputs.size(); ++i)
    {
      s << indent << "  digital_inputs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::niryo_robot_rpi::DigitalIO_<ContainerAllocator> >::stream(s, indent + "    ", v.digital_inputs[i]);
    }
    s << indent << "digital_outputs[]" << std::endl;
    for (size_t i = 0; i < v.digital_outputs.size(); ++i)
    {
      s << indent << "  digital_outputs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::niryo_robot_rpi::DigitalIO_<ContainerAllocator> >::stream(s, indent + "    ", v.digital_outputs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_RPI_MESSAGE_DIGITALIOSTATE_H
