// Generated by gencpp from file niryo_robot_rpi/LedBlinkerRequest.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_RPI_MESSAGE_LEDBLINKERREQUEST_H
#define NIRYO_ROBOT_RPI_MESSAGE_LEDBLINKERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_robot_rpi
{
template <class ContainerAllocator>
struct LedBlinkerRequest_
{
  typedef LedBlinkerRequest_<ContainerAllocator> Type;

  LedBlinkerRequest_()
    : activate(false)
    , frequency(0)
    , color(0)
    , blinker_duration(0.0)  {
    }
  LedBlinkerRequest_(const ContainerAllocator& _alloc)
    : activate(false)
    , frequency(0)
    , color(0)
    , blinker_duration(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _activate_type;
  _activate_type activate;

   typedef uint8_t _frequency_type;
  _frequency_type frequency;

   typedef uint8_t _color_type;
  _color_type color;

   typedef float _blinker_duration_type;
  _blinker_duration_type blinker_duration;



  enum {
    LED_OFF = 0u,
    LED_BLUE = 1u,
    LED_GREEN = 2u,
    LED_BLUE_GREEN = 3u,
    LED_RED = 4u,
    LED_PURPLE = 5u,
    LED_RED_GREEN = 6u,
    LED_WHITE = 7u,
  };


  typedef boost::shared_ptr< ::niryo_robot_rpi::LedBlinkerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_rpi::LedBlinkerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LedBlinkerRequest_

typedef ::niryo_robot_rpi::LedBlinkerRequest_<std::allocator<void> > LedBlinkerRequest;

typedef boost::shared_ptr< ::niryo_robot_rpi::LedBlinkerRequest > LedBlinkerRequestPtr;
typedef boost::shared_ptr< ::niryo_robot_rpi::LedBlinkerRequest const> LedBlinkerRequestConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_rpi::LedBlinkerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_rpi::LedBlinkerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace niryo_robot_rpi

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'niryo_robot_msgs': ['/home/niryo/catkin_ws/src/niryo_robot_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'niryo_robot_rpi': ['/home/niryo/catkin_ws/src/niryo_robot_rpi/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_rpi::LedBlinkerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_rpi::LedBlinkerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_rpi::LedBlinkerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_rpi::LedBlinkerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_rpi::LedBlinkerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_rpi::LedBlinkerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_rpi::LedBlinkerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fa3d8cedc0dae639a111323faa9bebec";
  }

  static const char* value(const ::niryo_robot_rpi::LedBlinkerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfa3d8cedc0dae639ULL;
  static const uint64_t static_value2 = 0xa111323faa9bebecULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_rpi::LedBlinkerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_rpi/LedBlinkerRequest";
  }

  static const char* value(const ::niryo_robot_rpi::LedBlinkerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_rpi::LedBlinkerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 LED_OFF = 0\n\
uint8 LED_BLUE = 1\n\
uint8 LED_GREEN = 2\n\
uint8 LED_BLUE_GREEN = 3\n\
uint8 LED_RED = 4\n\
uint8 LED_PURPLE = 5\n\
uint8 LED_RED_GREEN = 6\n\
uint8 LED_WHITE = 7\n\
\n\
bool activate\n\
uint8 frequency\n\
uint8 color\n\
float32 blinker_duration\n\
";
  }

  static const char* value(const ::niryo_robot_rpi::LedBlinkerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_rpi::LedBlinkerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.activate);
      stream.next(m.frequency);
      stream.next(m.color);
      stream.next(m.blinker_duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LedBlinkerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_rpi::LedBlinkerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_rpi::LedBlinkerRequest_<ContainerAllocator>& v)
  {
    s << indent << "activate: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.activate);
    s << indent << "frequency: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.frequency);
    s << indent << "color: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.color);
    s << indent << "blinker_duration: ";
    Printer<float>::stream(s, indent + "  ", v.blinker_duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_RPI_MESSAGE_LEDBLINKERREQUEST_H
