// Generated by gencpp from file niryo_robot_rpi/SetDigitalIORequest.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_RPI_MESSAGE_SETDIGITALIOREQUEST_H
#define NIRYO_ROBOT_RPI_MESSAGE_SETDIGITALIOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_robot_rpi
{
template <class ContainerAllocator>
struct SetDigitalIORequest_
{
  typedef SetDigitalIORequest_<ContainerAllocator> Type;

  SetDigitalIORequest_()
    : name()
    , value(false)  {
    }
  SetDigitalIORequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , value(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef uint8_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::niryo_robot_rpi::SetDigitalIORequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_rpi::SetDigitalIORequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetDigitalIORequest_

typedef ::niryo_robot_rpi::SetDigitalIORequest_<std::allocator<void> > SetDigitalIORequest;

typedef boost::shared_ptr< ::niryo_robot_rpi::SetDigitalIORequest > SetDigitalIORequestPtr;
typedef boost::shared_ptr< ::niryo_robot_rpi::SetDigitalIORequest const> SetDigitalIORequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_rpi::SetDigitalIORequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_rpi::SetDigitalIORequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace niryo_robot_rpi

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'niryo_robot_msgs': ['/home/niryo/catkin_ws/src/niryo_robot_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'niryo_robot_rpi': ['/home/niryo/catkin_ws/src/niryo_robot_rpi/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_rpi::SetDigitalIORequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_rpi::SetDigitalIORequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_rpi::SetDigitalIORequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_rpi::SetDigitalIORequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_rpi::SetDigitalIORequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_rpi::SetDigitalIORequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_rpi::SetDigitalIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23f05028c1a699fb83e22401228c3a9e";
  }

  static const char* value(const ::niryo_robot_rpi::SetDigitalIORequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23f05028c1a699fbULL;
  static const uint64_t static_value2 = 0x83e22401228c3a9eULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_rpi::SetDigitalIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_rpi/SetDigitalIORequest";
  }

  static const char* value(const ::niryo_robot_rpi::SetDigitalIORequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_rpi::SetDigitalIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
bool value\n\
\n\
";
  }

  static const char* value(const ::niryo_robot_rpi::SetDigitalIORequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_rpi::SetDigitalIORequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetDigitalIORequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_rpi::SetDigitalIORequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_rpi::SetDigitalIORequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_RPI_MESSAGE_SETDIGITALIOREQUEST_H
