// Generated by gencpp from file niryo_robot_vision/DebugMarkersRequest.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_VISION_MESSAGE_DEBUGMARKERSREQUEST_H
#define NIRYO_ROBOT_VISION_MESSAGE_DEBUGMARKERSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_robot_vision
{
template <class ContainerAllocator>
struct DebugMarkersRequest_
{
  typedef DebugMarkersRequest_<ContainerAllocator> Type;

  DebugMarkersRequest_()
    {
    }
  DebugMarkersRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::niryo_robot_vision::DebugMarkersRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_vision::DebugMarkersRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DebugMarkersRequest_

typedef ::niryo_robot_vision::DebugMarkersRequest_<std::allocator<void> > DebugMarkersRequest;

typedef boost::shared_ptr< ::niryo_robot_vision::DebugMarkersRequest > DebugMarkersRequestPtr;
typedef boost::shared_ptr< ::niryo_robot_vision::DebugMarkersRequest const> DebugMarkersRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_vision::DebugMarkersRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_vision::DebugMarkersRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace niryo_robot_vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'niryo_robot_msgs': ['/home/niryo/catkin_ws/src/niryo_robot_msgs/msg'], 'niryo_robot_vision': ['/home/niryo/catkin_ws/src/niryo_robot_vision/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_vision::DebugMarkersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_vision::DebugMarkersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_vision::DebugMarkersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_vision::DebugMarkersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_vision::DebugMarkersRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_vision::DebugMarkersRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_vision::DebugMarkersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::niryo_robot_vision::DebugMarkersRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_vision::DebugMarkersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_vision/DebugMarkersRequest";
  }

  static const char* value(const ::niryo_robot_vision::DebugMarkersRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_vision::DebugMarkersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::niryo_robot_vision::DebugMarkersRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_vision::DebugMarkersRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DebugMarkersRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_vision::DebugMarkersRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::niryo_robot_vision::DebugMarkersRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_VISION_MESSAGE_DEBUGMARKERSREQUEST_H
