// Generated by gencpp from file niryo_robot_vision/DebugMarkersResponse.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_VISION_MESSAGE_DEBUGMARKERSRESPONSE_H
#define NIRYO_ROBOT_VISION_MESSAGE_DEBUGMARKERSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/CompressedImage.h>

namespace niryo_robot_vision
{
template <class ContainerAllocator>
struct DebugMarkersResponse_
{
  typedef DebugMarkersResponse_<ContainerAllocator> Type;

  DebugMarkersResponse_()
    : markers_detected(false)
    , img()  {
    }
  DebugMarkersResponse_(const ContainerAllocator& _alloc)
    : markers_detected(false)
    , img(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _markers_detected_type;
  _markers_detected_type markers_detected;

   typedef  ::sensor_msgs::CompressedImage_<ContainerAllocator>  _img_type;
  _img_type img;





  typedef boost::shared_ptr< ::niryo_robot_vision::DebugMarkersResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_vision::DebugMarkersResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DebugMarkersResponse_

typedef ::niryo_robot_vision::DebugMarkersResponse_<std::allocator<void> > DebugMarkersResponse;

typedef boost::shared_ptr< ::niryo_robot_vision::DebugMarkersResponse > DebugMarkersResponsePtr;
typedef boost::shared_ptr< ::niryo_robot_vision::DebugMarkersResponse const> DebugMarkersResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_vision::DebugMarkersResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_vision::DebugMarkersResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace niryo_robot_vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'niryo_robot_msgs': ['/home/niryo/catkin_ws/src/niryo_robot_msgs/msg'], 'niryo_robot_vision': ['/home/niryo/catkin_ws/src/niryo_robot_vision/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_vision::DebugMarkersResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_vision::DebugMarkersResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_vision::DebugMarkersResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_vision::DebugMarkersResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_vision::DebugMarkersResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_vision::DebugMarkersResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_vision::DebugMarkersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "63758d5125879b809b9c2ee90cbc28ff";
  }

  static const char* value(const ::niryo_robot_vision::DebugMarkersResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x63758d5125879b80ULL;
  static const uint64_t static_value2 = 0x9b9c2ee90cbc28ffULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_vision::DebugMarkersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_vision/DebugMarkersResponse";
  }

  static const char* value(const ::niryo_robot_vision::DebugMarkersResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_vision::DebugMarkersResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool markers_detected\n\
sensor_msgs/CompressedImage img\n\
\n\
\n\
================================================================================\n\
MSG: sensor_msgs/CompressedImage\n\
# This message contains a compressed image\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of camera\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
\n\
string format        # Specifies the format of the data\n\
                     #   Acceptable values:\n\
                     #     jpeg, png\n\
uint8[] data         # Compressed image buffer\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::niryo_robot_vision::DebugMarkersResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_vision::DebugMarkersResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.markers_detected);
      stream.next(m.img);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DebugMarkersResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_vision::DebugMarkersResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_vision::DebugMarkersResponse_<ContainerAllocator>& v)
  {
    s << indent << "markers_detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.markers_detected);
    s << indent << "img: ";
    s << std::endl;
    Printer< ::sensor_msgs::CompressedImage_<ContainerAllocator> >::stream(s, indent + "  ", v.img);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_VISION_MESSAGE_DEBUGMARKERSRESPONSE_H
