// Generated by gencpp from file niryo_robot_led_ring/LedRingCurrentState.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_LED_RING_MESSAGE_LEDRINGCURRENTSTATE_H
#define NIRYO_ROBOT_LED_RING_MESSAGE_LEDRINGCURRENTSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/ColorRGBA.h>

namespace niryo_robot_led_ring
{
template <class ContainerAllocator>
struct LedRingCurrentState_
{
  typedef LedRingCurrentState_<ContainerAllocator> Type;

  LedRingCurrentState_()
    : header()
    , led_ring_colors()  {
    }
  LedRingCurrentState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , led_ring_colors(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::std_msgs::ColorRGBA_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::std_msgs::ColorRGBA_<ContainerAllocator> >::other >  _led_ring_colors_type;
  _led_ring_colors_type led_ring_colors;





  typedef boost::shared_ptr< ::niryo_robot_led_ring::LedRingCurrentState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_led_ring::LedRingCurrentState_<ContainerAllocator> const> ConstPtr;

}; // struct LedRingCurrentState_

typedef ::niryo_robot_led_ring::LedRingCurrentState_<std::allocator<void> > LedRingCurrentState;

typedef boost::shared_ptr< ::niryo_robot_led_ring::LedRingCurrentState > LedRingCurrentStatePtr;
typedef boost::shared_ptr< ::niryo_robot_led_ring::LedRingCurrentState const> LedRingCurrentStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_led_ring::LedRingCurrentState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_led_ring::LedRingCurrentState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace niryo_robot_led_ring

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'niryo_robot_msgs': ['/home/niryo/catkin_ws/src/niryo_robot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'niryo_robot_led_ring': ['/home/niryo/catkin_ws/src/niryo_robot_led_ring/msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_led_ring::LedRingCurrentState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_led_ring::LedRingCurrentState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_led_ring::LedRingCurrentState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_led_ring::LedRingCurrentState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_led_ring::LedRingCurrentState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_led_ring::LedRingCurrentState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_led_ring::LedRingCurrentState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef53709298b36af9705e7fb4631b8215";
  }

  static const char* value(const ::niryo_robot_led_ring::LedRingCurrentState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef53709298b36af9ULL;
  static const uint64_t static_value2 = 0x705e7fb4631b8215ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_led_ring::LedRingCurrentState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_led_ring/LedRingCurrentState";
  }

  static const char* value(const ::niryo_robot_led_ring::LedRingCurrentState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_led_ring::LedRingCurrentState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
std_msgs/ColorRGBA[] led_ring_colors\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: std_msgs/ColorRGBA\n\
float32 r\n\
float32 g\n\
float32 b\n\
float32 a\n\
";
  }

  static const char* value(const ::niryo_robot_led_ring::LedRingCurrentState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_led_ring::LedRingCurrentState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.led_ring_colors);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LedRingCurrentState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_led_ring::LedRingCurrentState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_led_ring::LedRingCurrentState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "led_ring_colors[]" << std::endl;
    for (size_t i = 0; i < v.led_ring_colors.size(); ++i)
    {
      s << indent << "  led_ring_colors[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::ColorRGBA_<ContainerAllocator> >::stream(s, indent + "    ", v.led_ring_colors[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_LED_RING_MESSAGE_LEDRINGCURRENTSTATE_H
