// Generated by gencpp from file can_driver/StepperCmdResponse.msg
// DO NOT EDIT!


#ifndef CAN_DRIVER_MESSAGE_STEPPERCMDRESPONSE_H
#define CAN_DRIVER_MESSAGE_STEPPERCMDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace can_driver
{
template <class ContainerAllocator>
struct StepperCmdResponse_
{
  typedef StepperCmdResponse_<ContainerAllocator> Type;

  StepperCmdResponse_()
    : result(false)  {
    }
  StepperCmdResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::can_driver::StepperCmdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::can_driver::StepperCmdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StepperCmdResponse_

typedef ::can_driver::StepperCmdResponse_<std::allocator<void> > StepperCmdResponse;

typedef boost::shared_ptr< ::can_driver::StepperCmdResponse > StepperCmdResponsePtr;
typedef boost::shared_ptr< ::can_driver::StepperCmdResponse const> StepperCmdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::can_driver::StepperCmdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::can_driver::StepperCmdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace can_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'niryo_robot_msgs': ['/home/niryo/catkin_ws/src/niryo_robot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'can_driver': ['/home/niryo/catkin_ws/src/niryo_robot_hardware_stack/can_driver/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::can_driver::StepperCmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::can_driver::StepperCmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_driver::StepperCmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_driver::StepperCmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_driver::StepperCmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_driver::StepperCmdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::can_driver::StepperCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::can_driver::StepperCmdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::can_driver::StepperCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "can_driver/StepperCmdResponse";
  }

  static const char* value(const ::can_driver::StepperCmdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::can_driver::StepperCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n\
";
  }

  static const char* value(const ::can_driver::StepperCmdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::can_driver::StepperCmdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StepperCmdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::can_driver::StepperCmdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::can_driver::StepperCmdResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAN_DRIVER_MESSAGE_STEPPERCMDRESPONSE_H
