// Generated by gencpp from file niryo_robot_msgs/CommandStatus.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_MSGS_MESSAGE_COMMANDSTATUS_H
#define NIRYO_ROBOT_MSGS_MESSAGE_COMMANDSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_robot_msgs
{
template <class ContainerAllocator>
struct CommandStatus_
{
  typedef CommandStatus_<ContainerAllocator> Type;

  CommandStatus_()
    : val(0)  {
    }
  CommandStatus_(const ContainerAllocator& _alloc)
    : val(0)  {
  (void)_alloc;
    }



   typedef int32_t _val_type;
  _val_type val;



  enum {
    SUCCESS = 1,
    CANCELLED = 2,
    PREEMPTED = 3,
    FAILURE = -1,
    ABORTED = -3,
    STOPPED = -4,
    BAD_HARDWARE_VERSION = -10,
    ROS_ERROR = -20,
    FILE_ALREADY_EXISTS = -30,
    UNKNOWN_COMMAND = -50,
    NOT_IMPLEMENTED_COMMAND = -51,
    INVALID_PARAMETERS = -52,
    HARDWARE_FAILURE = -110,
    HARDWARE_NOT_OK = -111,
    LEARNING_MODE_ON = -112,
    CALIBRATION_NOT_DONE = -113,
    DIGITAL_IO_PANEL_ERROR = -114,
    LED_MANAGER_ERROR = -115,
    BUTTON_ERROR = -116,
    WRONG_MOTOR_TYPE = -117,
    TTL_WRITE_ERROR = -118,
    TTL_READ_ERROR = -119,
    CAN_WRITE_ERROR = -120,
    CAN_READ_ERROR = -121,
    NO_CONVEYOR_LEFT = -122,
    NO_CONVEYOR_FOUND = -123,
    CONVEYOR_ID_INVALID = -124,
    CALIBRATION_IN_PROGRESS = -125,
    VIDEO_STREAM_ON_OFF_FAILURE = -170,
    VIDEO_STREAM_NOT_RUNNING = -171,
    OBJECT_NOT_FOUND = -172,
    MARKERS_NOT_FOUND = -173,
    ARM_COMMANDER_FAILURE = -220,
    GOAL_STILL_ACTIVE = -221,
    JOG_CONTROLLER_ENABLED = -222,
    CONTROLLER_PROBLEMS = -223,
    SHOULD_RESTART = -224,
    JOG_CONTROLLER_FAILURE = -225,
    PLAN_FAILED = -230,
    NO_PLAN_AVAILABLE = -231,
    INVERT_KINEMATICS_FAILURE = -232,
    TOOL_FAILURE = -251,
    TOOL_ID_INVALID = -252,
    TOOL_NOT_CONNECTED = -253,
    TOOL_ROS_INTERFACE_ERROR = -254,
    POSES_HANDLER_CREATION_FAILED = -300,
    POSES_HANDLER_REMOVAL_FAILED = -301,
    POSES_HANDLER_READ_FAILURE = -302,
    POSES_HANDLER_COMPUTE_FAILURE = -303,
    WORKSPACE_CREATION_FAILED = -308,
    PROGRAMS_MANAGER_FAILURE = -320,
    PROGRAMS_MANAGER_READ_FAILURE = -321,
    PROGRAMS_MANAGER_UNKNOWN_LANGUAGE = -325,
    PROGRAMS_MANAGER_NOT_RUNNABLE_LANGUAGE = -326,
    PROGRAMS_MANAGER_EXECUTION_FAILED = -327,
    PROGRAMS_MANAGER_STOPPING_FAILED = -328,
    PROGRAMS_MANAGER_AUTORUN_FAILURE = -329,
    PROGRAMS_MANAGER_WRITING_FAILURE = -330,
    PROGRAMS_MANAGER_FILE_ALREADY_EXISTS = -331,
    PROGRAMS_MANAGER_FILE_DOES_NOT_EXIST = -332,
    CREDENTIALS_FILE_ERROR = -400,
    CREDENTIALS_UNKNOWN_ERROR = -401,
    SYSTEM_API_CLIENT_UNKNOWN_ERROR = -440,
    SYSTEM_API_CLIENT_INVALID_ROBOT_NAME = -441,
    SYSTEM_API_CLIENT_REQUEST_FAILED = -442,
    SYSTEM_API_CLIENT_UNKNOWN_COMMAND = -443,
    SYSTEM_API_CLIENT_COMMAND_FAILED = -444,
    DATABASE_DB_ERROR = -460,
    DATABASE_SETTINGS_UNKNOWN = -461,
    DATABASE_SETTINGS_TYPE_MISMATCH = -462,
    DATABASE_FILE_PATH_UNKNOWN = -463,
    REPORTS_UNABLE_TO_SEND = -470,
    REPORTS_SENDING_FAIL = -471,
    REPORTS_FETCHING_FAIL = -472,
    SOUND_FILE_NOT_FOUND = -500,
    PROTECTED_SOUND_NAME = -501,
    INVALID_SOUND_NAME = -502,
    INVALID_SOUND_FORMAT = -503,
  };


  typedef boost::shared_ptr< ::niryo_robot_msgs::CommandStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_msgs::CommandStatus_<ContainerAllocator> const> ConstPtr;

}; // struct CommandStatus_

typedef ::niryo_robot_msgs::CommandStatus_<std::allocator<void> > CommandStatus;

typedef boost::shared_ptr< ::niryo_robot_msgs::CommandStatus > CommandStatusPtr;
typedef boost::shared_ptr< ::niryo_robot_msgs::CommandStatus const> CommandStatusConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_msgs::CommandStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_msgs::CommandStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace niryo_robot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'niryo_robot_msgs': ['/home/niryo/catkin_ws/src/niryo_robot_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_msgs::CommandStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_msgs::CommandStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_msgs::CommandStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_msgs::CommandStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_msgs::CommandStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_msgs::CommandStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_msgs::CommandStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "14425de8288e1ca7c999de958bd51b14";
  }

  static const char* value(const ::niryo_robot_msgs::CommandStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x14425de8288e1ca7ULL;
  static const uint64_t static_value2 = 0xc999de958bd51b14ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_msgs::CommandStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_msgs/CommandStatus";
  }

  static const char* value(const ::niryo_robot_msgs::CommandStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_msgs::CommandStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 val\n\
\n\
# overall behavior\n\
int32 SUCCESS = 1\n\
int32 CANCELLED = 2\n\
int32 PREEMPTED = 3\n\
\n\
int32 FAILURE = -1\n\
int32 ABORTED = -3\n\
int32 STOPPED = -4\n\
\n\
int32 BAD_HARDWARE_VERSION = -10\n\
int32 ROS_ERROR = -20\n\
\n\
int32 FILE_ALREADY_EXISTS = -30\n\
\n\
int32 UNKNOWN_COMMAND = -50\n\
int32 NOT_IMPLEMENTED_COMMAND = -51\n\
int32 INVALID_PARAMETERS = -52\n\
\n\
# - Hardware\n\
int32 HARDWARE_FAILURE = -110\n\
int32 HARDWARE_NOT_OK = -111\n\
int32 LEARNING_MODE_ON = -112\n\
int32 CALIBRATION_NOT_DONE = -113\n\
int32 DIGITAL_IO_PANEL_ERROR = -114\n\
int32 LED_MANAGER_ERROR = -115\n\
int32 BUTTON_ERROR = -116\n\
int32 WRONG_MOTOR_TYPE = -117\n\
int32 TTL_WRITE_ERROR = -118\n\
int32 TTL_READ_ERROR = -119\n\
int32 CAN_WRITE_ERROR = -120\n\
int32 CAN_READ_ERROR = -121\n\
int32 NO_CONVEYOR_LEFT = -122\n\
int32 NO_CONVEYOR_FOUND = -123\n\
int32 CONVEYOR_ID_INVALID = -124\n\
int32 CALIBRATION_IN_PROGRESS = -125\n\
\n\
# - Vision\n\
int32 VIDEO_STREAM_ON_OFF_FAILURE = -170\n\
int32 VIDEO_STREAM_NOT_RUNNING = -171\n\
int32 OBJECT_NOT_FOUND = -172\n\
int32 MARKERS_NOT_FOUND = -173\n\
\n\
# - Commander\n\
# Arm Commander\n\
int32 ARM_COMMANDER_FAILURE = -220\n\
int32 GOAL_STILL_ACTIVE = -221\n\
int32 JOG_CONTROLLER_ENABLED = -222\n\
int32 CONTROLLER_PROBLEMS = -223\n\
int32 SHOULD_RESTART = -224\n\
int32 JOG_CONTROLLER_FAILURE = -225\n\
\n\
int32 PLAN_FAILED = -230\n\
int32 NO_PLAN_AVAILABLE = -231\n\
int32 INVERT_KINEMATICS_FAILURE = -232\n\
\n\
# Tool Commander\n\
int32 TOOL_FAILURE = -251\n\
int32 TOOL_ID_INVALID = -252\n\
int32 TOOL_NOT_CONNECTED = -253\n\
int32 TOOL_ROS_INTERFACE_ERROR = -254\n\
\n\
# - Pose Handlers\n\
int32 POSES_HANDLER_CREATION_FAILED = -300\n\
int32 POSES_HANDLER_REMOVAL_FAILED = -301\n\
int32 POSES_HANDLER_READ_FAILURE = -302\n\
int32 POSES_HANDLER_COMPUTE_FAILURE = -303\n\
\n\
int32 WORKSPACE_CREATION_FAILED = -308\n\
\n\
# - Programs Manager\n\
int32 PROGRAMS_MANAGER_FAILURE = -320\n\
int32 PROGRAMS_MANAGER_READ_FAILURE = -321\n\
int32 PROGRAMS_MANAGER_UNKNOWN_LANGUAGE = -325\n\
int32 PROGRAMS_MANAGER_NOT_RUNNABLE_LANGUAGE = -326\n\
int32 PROGRAMS_MANAGER_EXECUTION_FAILED = -327\n\
int32 PROGRAMS_MANAGER_STOPPING_FAILED = -328\n\
int32 PROGRAMS_MANAGER_AUTORUN_FAILURE = -329\n\
int32 PROGRAMS_MANAGER_WRITING_FAILURE = -330\n\
int32 PROGRAMS_MANAGER_FILE_ALREADY_EXISTS = -331\n\
int32 PROGRAMS_MANAGER_FILE_DOES_NOT_EXIST = -332\n\
\n\
\n\
# - Credentials\n\
int32 CREDENTIALS_FILE_ERROR = -400\n\
int32 CREDENTIALS_UNKNOWN_ERROR = -401\n\
\n\
\n\
# - System Api Client\n\
int32 SYSTEM_API_CLIENT_UNKNOWN_ERROR = -440\n\
int32 SYSTEM_API_CLIENT_INVALID_ROBOT_NAME = -441\n\
int32 SYSTEM_API_CLIENT_REQUEST_FAILED = -442\n\
int32 SYSTEM_API_CLIENT_UNKNOWN_COMMAND = -443\n\
int32 SYSTEM_API_CLIENT_COMMAND_FAILED = -444\n\
\n\
# - Database\n\
int32 DATABASE_DB_ERROR = -460\n\
int32 DATABASE_SETTINGS_UNKNOWN = -461\n\
int32 DATABASE_SETTINGS_TYPE_MISMATCH = -462\n\
int32 DATABASE_FILE_PATH_UNKNOWN = -463\n\
\n\
\n\
# - Reports\n\
int32 REPORTS_UNABLE_TO_SEND = -470\n\
int32 REPORTS_SENDING_FAIL = -471\n\
int32 REPORTS_FETCHING_FAIL = -472\n\
\n\
# - Sound interface\n\
int32 SOUND_FILE_NOT_FOUND = -500\n\
int32 PROTECTED_SOUND_NAME = -501\n\
int32 INVALID_SOUND_NAME = -502\n\
int32 INVALID_SOUND_FORMAT = -503\n\
";
  }

  static const char* value(const ::niryo_robot_msgs::CommandStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_msgs::CommandStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.val);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommandStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_msgs::CommandStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_msgs::CommandStatus_<ContainerAllocator>& v)
  {
    s << indent << "val: ";
    Printer<int32_t>::stream(s, indent + "  ", v.val);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_MSGS_MESSAGE_COMMANDSTATUS_H
