// Generated by gencpp from file niryo_robot_poses_handlers/GetWorkspaceRobotPosesResponse.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_POSES_HANDLERS_MESSAGE_GETWORKSPACEROBOTPOSESRESPONSE_H
#define NIRYO_ROBOT_POSES_HANDLERS_MESSAGE_GETWORKSPACEROBOTPOSESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <niryo_robot_msgs/RobotState.h>

namespace niryo_robot_poses_handlers
{
template <class ContainerAllocator>
struct GetWorkspaceRobotPosesResponse_
{
  typedef GetWorkspaceRobotPosesResponse_<ContainerAllocator> Type;

  GetWorkspaceRobotPosesResponse_()
    : status(0)
    , message()
    , poses()  {
    }
  GetWorkspaceRobotPosesResponse_(const ContainerAllocator& _alloc)
    : status(0)
    , message(_alloc)
    , poses(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef std::vector< ::niryo_robot_msgs::RobotState_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::niryo_robot_msgs::RobotState_<ContainerAllocator> >::other >  _poses_type;
  _poses_type poses;





  typedef boost::shared_ptr< ::niryo_robot_poses_handlers::GetWorkspaceRobotPosesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_poses_handlers::GetWorkspaceRobotPosesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetWorkspaceRobotPosesResponse_

typedef ::niryo_robot_poses_handlers::GetWorkspaceRobotPosesResponse_<std::allocator<void> > GetWorkspaceRobotPosesResponse;

typedef boost::shared_ptr< ::niryo_robot_poses_handlers::GetWorkspaceRobotPosesResponse > GetWorkspaceRobotPosesResponsePtr;
typedef boost::shared_ptr< ::niryo_robot_poses_handlers::GetWorkspaceRobotPosesResponse const> GetWorkspaceRobotPosesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_poses_handlers::GetWorkspaceRobotPosesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_poses_handlers::GetWorkspaceRobotPosesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace niryo_robot_poses_handlers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'shape_msgs': ['/opt/ros/kinetic/share/shape_msgs/cmake/../msg'], 'niryo_robot_poses_handlers': ['/home/niryo/catkin_ws/src/niryo_robot_poses_handlers/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'moveit_msgs': ['/opt/ros/kinetic/share/moveit_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/kinetic/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/kinetic/share/octomap_msgs/cmake/../msg'], 'niryo_robot_msgs': ['/home/niryo/catkin_ws/src/niryo_robot_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_poses_handlers::GetWorkspaceRobotPosesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_poses_handlers::GetWorkspaceRobotPosesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_poses_handlers::GetWorkspaceRobotPosesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_poses_handlers::GetWorkspaceRobotPosesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_poses_handlers::GetWorkspaceRobotPosesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_poses_handlers::GetWorkspaceRobotPosesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_poses_handlers::GetWorkspaceRobotPosesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ceb77c4f9af2e9ceff0c6beb5efb70d2";
  }

  static const char* value(const ::niryo_robot_poses_handlers::GetWorkspaceRobotPosesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xceb77c4f9af2e9ceULL;
  static const uint64_t static_value2 = 0xff0c6beb5efb70d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_poses_handlers::GetWorkspaceRobotPosesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_poses_handlers/GetWorkspaceRobotPosesResponse";
  }

  static const char* value(const ::niryo_robot_poses_handlers::GetWorkspaceRobotPosesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_poses_handlers::GetWorkspaceRobotPosesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 status\n\
string message\n\
niryo_robot_msgs/RobotState[] poses\n\
\n\
\n\
================================================================================\n\
MSG: niryo_robot_msgs/RobotState\n\
geometry_msgs/Point position\n\
niryo_robot_msgs/RPY rpy\n\
geometry_msgs/Quaternion orientation\n\
\n\
geometry_msgs/Twist twist\n\
float64 tcp_speed\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: niryo_robot_msgs/RPY\n\
# roll, pitch and yaw\n\
\n\
float64 roll\n\
float64 pitch\n\
float64 yaw\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::niryo_robot_poses_handlers::GetWorkspaceRobotPosesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_poses_handlers::GetWorkspaceRobotPosesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.message);
      stream.next(m.poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetWorkspaceRobotPosesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_poses_handlers::GetWorkspaceRobotPosesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_poses_handlers::GetWorkspaceRobotPosesResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::niryo_robot_msgs::RobotState_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_POSES_HANDLERS_MESSAGE_GETWORKSPACEROBOTPOSESRESPONSE_H
