// Generated by gencpp from file niryo_robot_poses_handlers/ManageWorkspaceRequest.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_POSES_HANDLERS_MESSAGE_MANAGEWORKSPACEREQUEST_H
#define NIRYO_ROBOT_POSES_HANDLERS_MESSAGE_MANAGEWORKSPACEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <niryo_robot_poses_handlers/Workspace.h>

namespace niryo_robot_poses_handlers
{
template <class ContainerAllocator>
struct ManageWorkspaceRequest_
{
  typedef ManageWorkspaceRequest_<ContainerAllocator> Type;

  ManageWorkspaceRequest_()
    : cmd(0)
    , workspace()  {
    }
  ManageWorkspaceRequest_(const ContainerAllocator& _alloc)
    : cmd(0)
    , workspace(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _cmd_type;
  _cmd_type cmd;

   typedef  ::niryo_robot_poses_handlers::Workspace_<ContainerAllocator>  _workspace_type;
  _workspace_type workspace;



  enum {
    SAVE = 1,
    SAVE_WITH_POINTS = 2,
    DELETE = -1,
  };


  typedef boost::shared_ptr< ::niryo_robot_poses_handlers::ManageWorkspaceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_poses_handlers::ManageWorkspaceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ManageWorkspaceRequest_

typedef ::niryo_robot_poses_handlers::ManageWorkspaceRequest_<std::allocator<void> > ManageWorkspaceRequest;

typedef boost::shared_ptr< ::niryo_robot_poses_handlers::ManageWorkspaceRequest > ManageWorkspaceRequestPtr;
typedef boost::shared_ptr< ::niryo_robot_poses_handlers::ManageWorkspaceRequest const> ManageWorkspaceRequestConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_poses_handlers::ManageWorkspaceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_poses_handlers::ManageWorkspaceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace niryo_robot_poses_handlers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'shape_msgs': ['/opt/ros/kinetic/share/shape_msgs/cmake/../msg'], 'niryo_robot_poses_handlers': ['/home/niryo/catkin_ws/src/niryo_robot_poses_handlers/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'moveit_msgs': ['/opt/ros/kinetic/share/moveit_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/kinetic/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/kinetic/share/octomap_msgs/cmake/../msg'], 'niryo_robot_msgs': ['/home/niryo/catkin_ws/src/niryo_robot_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_poses_handlers::ManageWorkspaceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_poses_handlers::ManageWorkspaceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_poses_handlers::ManageWorkspaceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_poses_handlers::ManageWorkspaceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_poses_handlers::ManageWorkspaceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_poses_handlers::ManageWorkspaceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_poses_handlers::ManageWorkspaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f2c2460cba0c7ca7f95697e66028f8c9";
  }

  static const char* value(const ::niryo_robot_poses_handlers::ManageWorkspaceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf2c2460cba0c7ca7ULL;
  static const uint64_t static_value2 = 0xf95697e66028f8c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_poses_handlers::ManageWorkspaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_poses_handlers/ManageWorkspaceRequest";
  }

  static const char* value(const ::niryo_robot_poses_handlers::ManageWorkspaceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_poses_handlers::ManageWorkspaceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 SAVE = 1\n\
int32 SAVE_WITH_POINTS = 2\n\
int32 DELETE = -1\n\
\n\
int32 cmd\n\
\n\
niryo_robot_poses_handlers/Workspace workspace\n\
\n\
\n\
================================================================================\n\
MSG: niryo_robot_poses_handlers/Workspace\n\
string name # maximum lenght of workspace's name is 30 characters\n\
string description\n\
\n\
geometry_msgs/Point[] points\n\
niryo_robot_msgs/RobotState[] poses\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: niryo_robot_msgs/RobotState\n\
geometry_msgs/Point position\n\
niryo_robot_msgs/RPY rpy\n\
geometry_msgs/Quaternion orientation\n\
\n\
geometry_msgs/Twist twist\n\
float64 tcp_speed\n\
================================================================================\n\
MSG: niryo_robot_msgs/RPY\n\
# roll, pitch and yaw\n\
\n\
float64 roll\n\
float64 pitch\n\
float64 yaw\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::niryo_robot_poses_handlers::ManageWorkspaceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_poses_handlers::ManageWorkspaceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
      stream.next(m.workspace);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ManageWorkspaceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_poses_handlers::ManageWorkspaceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_poses_handlers::ManageWorkspaceRequest_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cmd);
    s << indent << "workspace: ";
    s << std::endl;
    Printer< ::niryo_robot_poses_handlers::Workspace_<ContainerAllocator> >::stream(s, indent + "  ", v.workspace);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_POSES_HANDLERS_MESSAGE_MANAGEWORKSPACEREQUEST_H
