// Generated by gencpp from file ttl_driver/CollisionStatus.msg
// DO NOT EDIT!


#ifndef TTL_DRIVER_MESSAGE_COLLISIONSTATUS_H
#define TTL_DRIVER_MESSAGE_COLLISIONSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ttl_driver
{
template <class ContainerAllocator>
struct CollisionStatus_
{
  typedef CollisionStatus_<ContainerAllocator> Type;

  CollisionStatus_()
    : collision_detected(false)  {
    }
  CollisionStatus_(const ContainerAllocator& _alloc)
    : collision_detected(false)  {
  (void)_alloc;
    }



   typedef uint8_t _collision_detected_type;
  _collision_detected_type collision_detected;





  typedef boost::shared_ptr< ::ttl_driver::CollisionStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ttl_driver::CollisionStatus_<ContainerAllocator> const> ConstPtr;

}; // struct CollisionStatus_

typedef ::ttl_driver::CollisionStatus_<std::allocator<void> > CollisionStatus;

typedef boost::shared_ptr< ::ttl_driver::CollisionStatus > CollisionStatusPtr;
typedef boost::shared_ptr< ::ttl_driver::CollisionStatus const> CollisionStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ttl_driver::CollisionStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ttl_driver::CollisionStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ttl_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'niryo_robot_msgs': ['/home/niryo/catkin_ws/src/niryo_robot_msgs/msg'], 'ttl_driver': ['/home/niryo/catkin_ws/src/niryo_robot_hardware_stack/ttl_driver/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ttl_driver::CollisionStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ttl_driver::CollisionStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ttl_driver::CollisionStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ttl_driver::CollisionStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ttl_driver::CollisionStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ttl_driver::CollisionStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ttl_driver::CollisionStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "606738ba52239151e427349a94bbafbf";
  }

  static const char* value(const ::ttl_driver::CollisionStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x606738ba52239151ULL;
  static const uint64_t static_value2 = 0xe427349a94bbafbfULL;
};

template<class ContainerAllocator>
struct DataType< ::ttl_driver::CollisionStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ttl_driver/CollisionStatus";
  }

  static const char* value(const ::ttl_driver::CollisionStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ttl_driver::CollisionStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool collision_detected\n\
";
  }

  static const char* value(const ::ttl_driver::CollisionStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ttl_driver::CollisionStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.collision_detected);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CollisionStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ttl_driver::CollisionStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ttl_driver::CollisionStatus_<ContainerAllocator>& v)
  {
    s << indent << "collision_detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.collision_detected);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TTL_DRIVER_MESSAGE_COLLISIONSTATUS_H
