// Generated by gencpp from file ttl_driver/MotorCommand.msg
// DO NOT EDIT!


#ifndef TTL_DRIVER_MESSAGE_MOTORCOMMAND_H
#define TTL_DRIVER_MESSAGE_MOTORCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ttl_driver
{
template <class ContainerAllocator>
struct MotorCommand_
{
  typedef MotorCommand_<ContainerAllocator> Type;

  MotorCommand_()
    : cmd_type(0)
    , motors_id()
    , params()  {
    }
  MotorCommand_(const ContainerAllocator& _alloc)
    : cmd_type(0)
    , motors_id(_alloc)
    , params(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _cmd_type_type;
  _cmd_type_type cmd_type;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _motors_id_type;
  _motors_id_type motors_id;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _params_type;
  _params_type params;



  enum {
    CMD_TYPE_POSITION = 1u,
    CMD_TYPE_VELOCITY = 2u,
    CMD_TYPE_EFFORT = 3u,
    CMD_TYPE_TORQUE = 4u,
  };


  typedef boost::shared_ptr< ::ttl_driver::MotorCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ttl_driver::MotorCommand_<ContainerAllocator> const> ConstPtr;

}; // struct MotorCommand_

typedef ::ttl_driver::MotorCommand_<std::allocator<void> > MotorCommand;

typedef boost::shared_ptr< ::ttl_driver::MotorCommand > MotorCommandPtr;
typedef boost::shared_ptr< ::ttl_driver::MotorCommand const> MotorCommandConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ttl_driver::MotorCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ttl_driver::MotorCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ttl_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'niryo_robot_msgs': ['/home/niryo/catkin_ws/src/niryo_robot_msgs/msg'], 'ttl_driver': ['/home/niryo/catkin_ws/src/niryo_robot_hardware_stack/ttl_driver/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ttl_driver::MotorCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ttl_driver::MotorCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ttl_driver::MotorCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ttl_driver::MotorCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ttl_driver::MotorCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ttl_driver::MotorCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ttl_driver::MotorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1fd0ce1ecaa67db6efa4b24d2606e47b";
  }

  static const char* value(const ::ttl_driver::MotorCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1fd0ce1ecaa67db6ULL;
  static const uint64_t static_value2 = 0xefa4b24d2606e47bULL;
};

template<class ContainerAllocator>
struct DataType< ::ttl_driver::MotorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ttl_driver/MotorCommand";
  }

  static const char* value(const ::ttl_driver::MotorCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ttl_driver::MotorCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 cmd_type\n\
uint8 CMD_TYPE_POSITION=1\n\
uint8 CMD_TYPE_VELOCITY=2\n\
uint8 CMD_TYPE_EFFORT=3\n\
uint8 CMD_TYPE_TORQUE=4\n\
\n\
uint8[] motors_id\n\
uint32[] params\n\
";
  }

  static const char* value(const ::ttl_driver::MotorCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ttl_driver::MotorCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd_type);
      stream.next(m.motors_id);
      stream.next(m.params);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ttl_driver::MotorCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ttl_driver::MotorCommand_<ContainerAllocator>& v)
  {
    s << indent << "cmd_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cmd_type);
    s << indent << "motors_id[]" << std::endl;
    for (size_t i = 0; i < v.motors_id.size(); ++i)
    {
      s << indent << "  motors_id[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.motors_id[i]);
    }
    s << indent << "params[]" << std::endl;
    for (size_t i = 0; i < v.params.size(); ++i)
    {
      s << indent << "  params[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.params[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TTL_DRIVER_MESSAGE_MOTORCOMMAND_H
