// Generated by gencpp from file ttl_driver/ReadVelocityProfileRequest.msg
// DO NOT EDIT!


#ifndef TTL_DRIVER_MESSAGE_READVELOCITYPROFILEREQUEST_H
#define TTL_DRIVER_MESSAGE_READVELOCITYPROFILEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ttl_driver
{
template <class ContainerAllocator>
struct ReadVelocityProfileRequest_
{
  typedef ReadVelocityProfileRequest_<ContainerAllocator> Type;

  ReadVelocityProfileRequest_()
    : id(0)  {
    }
  ReadVelocityProfileRequest_(const ContainerAllocator& _alloc)
    : id(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::ttl_driver::ReadVelocityProfileRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ttl_driver::ReadVelocityProfileRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ReadVelocityProfileRequest_

typedef ::ttl_driver::ReadVelocityProfileRequest_<std::allocator<void> > ReadVelocityProfileRequest;

typedef boost::shared_ptr< ::ttl_driver::ReadVelocityProfileRequest > ReadVelocityProfileRequestPtr;
typedef boost::shared_ptr< ::ttl_driver::ReadVelocityProfileRequest const> ReadVelocityProfileRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ttl_driver::ReadVelocityProfileRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ttl_driver::ReadVelocityProfileRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ttl_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'niryo_robot_msgs': ['/home/niryo/catkin_ws/src/niryo_robot_msgs/msg'], 'ttl_driver': ['/home/niryo/catkin_ws/src/niryo_robot_hardware_stack/ttl_driver/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ttl_driver::ReadVelocityProfileRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ttl_driver::ReadVelocityProfileRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ttl_driver::ReadVelocityProfileRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ttl_driver::ReadVelocityProfileRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ttl_driver::ReadVelocityProfileRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ttl_driver::ReadVelocityProfileRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ttl_driver::ReadVelocityProfileRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "541b98e964705918fa8eb206b65347b3";
  }

  static const char* value(const ::ttl_driver::ReadVelocityProfileRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x541b98e964705918ULL;
  static const uint64_t static_value2 = 0xfa8eb206b65347b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::ttl_driver::ReadVelocityProfileRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ttl_driver/ReadVelocityProfileRequest";
  }

  static const char* value(const ::ttl_driver::ReadVelocityProfileRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ttl_driver::ReadVelocityProfileRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
uint8 id\n\
";
  }

  static const char* value(const ::ttl_driver::ReadVelocityProfileRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ttl_driver::ReadVelocityProfileRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReadVelocityProfileRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ttl_driver::ReadVelocityProfileRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ttl_driver::ReadVelocityProfileRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TTL_DRIVER_MESSAGE_READVELOCITYPROFILEREQUEST_H
