// Generated by gencpp from file ttl_driver/ReadVelocityProfileResponse.msg
// DO NOT EDIT!


#ifndef TTL_DRIVER_MESSAGE_READVELOCITYPROFILERESPONSE_H
#define TTL_DRIVER_MESSAGE_READVELOCITYPROFILERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ttl_driver
{
template <class ContainerAllocator>
struct ReadVelocityProfileResponse_
{
  typedef ReadVelocityProfileResponse_<ContainerAllocator> Type;

  ReadVelocityProfileResponse_()
    : v_start(0)
    , a_1(0)
    , v_1(0)
    , a_max(0)
    , v_max(0)
    , d_max(0)
    , d_1(0)
    , v_stop(0)
    , status(0)
    , message()  {
    }
  ReadVelocityProfileResponse_(const ContainerAllocator& _alloc)
    : v_start(0)
    , a_1(0)
    , v_1(0)
    , a_max(0)
    , v_max(0)
    , d_max(0)
    , d_1(0)
    , v_stop(0)
    , status(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _v_start_type;
  _v_start_type v_start;

   typedef uint32_t _a_1_type;
  _a_1_type a_1;

   typedef uint32_t _v_1_type;
  _v_1_type v_1;

   typedef uint32_t _a_max_type;
  _a_max_type a_max;

   typedef uint32_t _v_max_type;
  _v_max_type v_max;

   typedef uint32_t _d_max_type;
  _d_max_type d_max;

   typedef uint32_t _d_1_type;
  _d_1_type d_1;

   typedef uint32_t _v_stop_type;
  _v_stop_type v_stop;

   typedef int32_t _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ReadVelocityProfileResponse_

typedef ::ttl_driver::ReadVelocityProfileResponse_<std::allocator<void> > ReadVelocityProfileResponse;

typedef boost::shared_ptr< ::ttl_driver::ReadVelocityProfileResponse > ReadVelocityProfileResponsePtr;
typedef boost::shared_ptr< ::ttl_driver::ReadVelocityProfileResponse const> ReadVelocityProfileResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ttl_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'niryo_robot_msgs': ['/home/niryo/catkin_ws/src/niryo_robot_msgs/msg'], 'ttl_driver': ['/home/niryo/catkin_ws/src/niryo_robot_hardware_stack/ttl_driver/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3fb7d4f3462e29037ed19af3af05a999";
  }

  static const char* value(const ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3fb7d4f3462e2903ULL;
  static const uint64_t static_value2 = 0x7ed19af3af05a999ULL;
};

template<class ContainerAllocator>
struct DataType< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ttl_driver/ReadVelocityProfileResponse";
  }

  static const char* value(const ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 v_start\n\
\n\
uint32 a_1\n\
uint32 v_1\n\
\n\
uint32 a_max\n\
uint32 v_max\n\
uint32 d_max\n\
\n\
uint32 d_1\n\
\n\
uint32 v_stop\n\
\n\
int32 status\n\
string message\n\
\n\
";
  }

  static const char* value(const ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.v_start);
      stream.next(m.a_1);
      stream.next(m.v_1);
      stream.next(m.a_max);
      stream.next(m.v_max);
      stream.next(m.d_max);
      stream.next(m.d_1);
      stream.next(m.v_stop);
      stream.next(m.status);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReadVelocityProfileResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator>& v)
  {
    s << indent << "v_start: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.v_start);
    s << indent << "a_1: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.a_1);
    s << indent << "v_1: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.v_1);
    s << indent << "a_max: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.a_max);
    s << indent << "v_max: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.v_max);
    s << indent << "d_max: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.d_max);
    s << indent << "d_1: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.d_1);
    s << indent << "v_stop: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.v_stop);
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TTL_DRIVER_MESSAGE_READVELOCITYPROFILERESPONSE_H
