// Generated by gencpp from file ttl_driver/ReadCustomValueRequest.msg
// DO NOT EDIT!


#ifndef TTL_DRIVER_MESSAGE_READCUSTOMVALUEREQUEST_H
#define TTL_DRIVER_MESSAGE_READCUSTOMVALUEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ttl_driver
{
template <class ContainerAllocator>
struct ReadCustomValueRequest_
{
  typedef ReadCustomValueRequest_<ContainerAllocator> Type;

  ReadCustomValueRequest_()
    : id(0)
    , reg_address(0)
    , byte_number(0)  {
    }
  ReadCustomValueRequest_(const ContainerAllocator& _alloc)
    : id(0)
    , reg_address(0)
    , byte_number(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef int32_t _reg_address_type;
  _reg_address_type reg_address;

   typedef int32_t _byte_number_type;
  _byte_number_type byte_number;





  typedef boost::shared_ptr< ::ttl_driver::ReadCustomValueRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ttl_driver::ReadCustomValueRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ReadCustomValueRequest_

typedef ::ttl_driver::ReadCustomValueRequest_<std::allocator<void> > ReadCustomValueRequest;

typedef boost::shared_ptr< ::ttl_driver::ReadCustomValueRequest > ReadCustomValueRequestPtr;
typedef boost::shared_ptr< ::ttl_driver::ReadCustomValueRequest const> ReadCustomValueRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ttl_driver::ReadCustomValueRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ttl_driver::ReadCustomValueRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ttl_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'niryo_robot_msgs': ['/home/niryo/catkin_ws/src/niryo_robot_msgs/msg'], 'ttl_driver': ['/home/niryo/catkin_ws/src/niryo_robot_hardware_stack/ttl_driver/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ttl_driver::ReadCustomValueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ttl_driver::ReadCustomValueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ttl_driver::ReadCustomValueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ttl_driver::ReadCustomValueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ttl_driver::ReadCustomValueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ttl_driver::ReadCustomValueRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ttl_driver::ReadCustomValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "248e2f1be517216d9caade870f501e8d";
  }

  static const char* value(const ::ttl_driver::ReadCustomValueRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x248e2f1be517216dULL;
  static const uint64_t static_value2 = 0x9caade870f501e8dULL;
};

template<class ContainerAllocator>
struct DataType< ::ttl_driver::ReadCustomValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ttl_driver/ReadCustomValueRequest";
  }

  static const char* value(const ::ttl_driver::ReadCustomValueRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ttl_driver::ReadCustomValueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
uint8 id\n\
int32 reg_address\n\
int32 byte_number\n\
";
  }

  static const char* value(const ::ttl_driver::ReadCustomValueRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ttl_driver::ReadCustomValueRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.reg_address);
      stream.next(m.byte_number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReadCustomValueRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ttl_driver::ReadCustomValueRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ttl_driver::ReadCustomValueRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "reg_address: ";
    Printer<int32_t>::stream(s, indent + "  ", v.reg_address);
    s << indent << "byte_number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.byte_number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TTL_DRIVER_MESSAGE_READCUSTOMVALUEREQUEST_H
