// Generated by gencpp from file conveyor_interface/SetConveyorResponse.msg
// DO NOT EDIT!


#ifndef CONVEYOR_INTERFACE_MESSAGE_SETCONVEYORRESPONSE_H
#define CONVEYOR_INTERFACE_MESSAGE_SETCONVEYORRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace conveyor_interface
{
template <class ContainerAllocator>
struct SetConveyorResponse_
{
  typedef SetConveyorResponse_<ContainerAllocator> Type;

  SetConveyorResponse_()
    : id(0)
    , status(0)
    , message()  {
    }
  SetConveyorResponse_(const ContainerAllocator& _alloc)
    : id(0)
    , status(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef int16_t _id_type;
  _id_type id;

   typedef int16_t _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::conveyor_interface::SetConveyorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::conveyor_interface::SetConveyorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetConveyorResponse_

typedef ::conveyor_interface::SetConveyorResponse_<std::allocator<void> > SetConveyorResponse;

typedef boost::shared_ptr< ::conveyor_interface::SetConveyorResponse > SetConveyorResponsePtr;
typedef boost::shared_ptr< ::conveyor_interface::SetConveyorResponse const> SetConveyorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::conveyor_interface::SetConveyorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::conveyor_interface::SetConveyorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace conveyor_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'conveyor_interface': ['/home/niryo/catkin_ws/src/niryo_robot_hardware_stack/conveyor_interface/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::conveyor_interface::SetConveyorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::conveyor_interface::SetConveyorResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::conveyor_interface::SetConveyorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::conveyor_interface::SetConveyorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::conveyor_interface::SetConveyorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::conveyor_interface::SetConveyorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::conveyor_interface::SetConveyorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0d0c03464bbf1f4ce150329847e7eff6";
  }

  static const char* value(const ::conveyor_interface::SetConveyorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0d0c03464bbf1f4cULL;
  static const uint64_t static_value2 = 0xe150329847e7eff6ULL;
};

template<class ContainerAllocator>
struct DataType< ::conveyor_interface::SetConveyorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "conveyor_interface/SetConveyorResponse";
  }

  static const char* value(const ::conveyor_interface::SetConveyorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::conveyor_interface::SetConveyorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 id\n\
int16 status\n\
string message\n\
\n\
";
  }

  static const char* value(const ::conveyor_interface::SetConveyorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::conveyor_interface::SetConveyorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.status);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetConveyorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::conveyor_interface::SetConveyorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::conveyor_interface::SetConveyorResponse_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
    s << indent << "status: ";
    Printer<int16_t>::stream(s, indent + "  ", v.status);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONVEYOR_INTERFACE_MESSAGE_SETCONVEYORRESPONSE_H
