// Generated by gencpp from file niryo_robot_programs_manager/GetProgramResponse.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_PROGRAMS_MANAGER_MESSAGE_GETPROGRAMRESPONSE_H
#define NIRYO_ROBOT_PROGRAMS_MANAGER_MESSAGE_GETPROGRAMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_robot_programs_manager
{
template <class ContainerAllocator>
struct GetProgramResponse_
{
  typedef GetProgramResponse_<ContainerAllocator> Type;

  GetProgramResponse_()
    : status(0)
    , message()
    , code()
    , description()  {
    }
  GetProgramResponse_(const ContainerAllocator& _alloc)
    : status(0)
    , message(_alloc)
    , code(_alloc)
    , description(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _code_type;
  _code_type code;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _description_type;
  _description_type description;





  typedef boost::shared_ptr< ::niryo_robot_programs_manager::GetProgramResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_programs_manager::GetProgramResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetProgramResponse_

typedef ::niryo_robot_programs_manager::GetProgramResponse_<std::allocator<void> > GetProgramResponse;

typedef boost::shared_ptr< ::niryo_robot_programs_manager::GetProgramResponse > GetProgramResponsePtr;
typedef boost::shared_ptr< ::niryo_robot_programs_manager::GetProgramResponse const> GetProgramResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_programs_manager::GetProgramResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_programs_manager::GetProgramResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace niryo_robot_programs_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'niryo_robot_programs_manager': ['/home/niryo/catkin_ws/src/niryo_robot_programs_manager/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_programs_manager::GetProgramResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_programs_manager::GetProgramResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_programs_manager::GetProgramResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_programs_manager::GetProgramResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_programs_manager::GetProgramResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_programs_manager::GetProgramResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_programs_manager::GetProgramResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0784f34f0b60068c6280a1752e65fdb8";
  }

  static const char* value(const ::niryo_robot_programs_manager::GetProgramResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0784f34f0b60068cULL;
  static const uint64_t static_value2 = 0x6280a1752e65fdb8ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_programs_manager::GetProgramResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_programs_manager/GetProgramResponse";
  }

  static const char* value(const ::niryo_robot_programs_manager::GetProgramResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_programs_manager::GetProgramResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 status\n\
string message\n\
\n\
string code\n\
string description\n\
\n\
";
  }

  static const char* value(const ::niryo_robot_programs_manager::GetProgramResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_programs_manager::GetProgramResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.message);
      stream.next(m.code);
      stream.next(m.description);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetProgramResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_programs_manager::GetProgramResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_programs_manager::GetProgramResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "code: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.code);
    s << indent << "description: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.description);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_PROGRAMS_MANAGER_MESSAGE_GETPROGRAMRESPONSE_H
