// Generated by gencpp from file niryo_robot_programs_manager/ProgramLanguageList.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_PROGRAMS_MANAGER_MESSAGE_PROGRAMLANGUAGELIST_H
#define NIRYO_ROBOT_PROGRAMS_MANAGER_MESSAGE_PROGRAMLANGUAGELIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <niryo_robot_programs_manager/ProgramLanguage.h>

namespace niryo_robot_programs_manager
{
template <class ContainerAllocator>
struct ProgramLanguageList_
{
  typedef ProgramLanguageList_<ContainerAllocator> Type;

  ProgramLanguageList_()
    : language_list()  {
    }
  ProgramLanguageList_(const ContainerAllocator& _alloc)
    : language_list(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::niryo_robot_programs_manager::ProgramLanguage_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::niryo_robot_programs_manager::ProgramLanguage_<ContainerAllocator> >::other >  _language_list_type;
  _language_list_type language_list;





  typedef boost::shared_ptr< ::niryo_robot_programs_manager::ProgramLanguageList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_programs_manager::ProgramLanguageList_<ContainerAllocator> const> ConstPtr;

}; // struct ProgramLanguageList_

typedef ::niryo_robot_programs_manager::ProgramLanguageList_<std::allocator<void> > ProgramLanguageList;

typedef boost::shared_ptr< ::niryo_robot_programs_manager::ProgramLanguageList > ProgramLanguageListPtr;
typedef boost::shared_ptr< ::niryo_robot_programs_manager::ProgramLanguageList const> ProgramLanguageListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_programs_manager::ProgramLanguageList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_programs_manager::ProgramLanguageList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace niryo_robot_programs_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'niryo_robot_programs_manager': ['/home/niryo/catkin_ws/src/niryo_robot_programs_manager/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_programs_manager::ProgramLanguageList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_programs_manager::ProgramLanguageList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_programs_manager::ProgramLanguageList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_programs_manager::ProgramLanguageList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_programs_manager::ProgramLanguageList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_programs_manager::ProgramLanguageList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_programs_manager::ProgramLanguageList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3bb60a31107853c4b43f43c3afc8faf";
  }

  static const char* value(const ::niryo_robot_programs_manager::ProgramLanguageList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3bb60a31107853cULL;
  static const uint64_t static_value2 = 0x4b43f43c3afc8fafULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_programs_manager::ProgramLanguageList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_programs_manager/ProgramLanguageList";
  }

  static const char* value(const ::niryo_robot_programs_manager::ProgramLanguageList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_programs_manager::ProgramLanguageList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_programs_manager/ProgramLanguage[] language_list\n\
\n\
================================================================================\n\
MSG: niryo_robot_programs_manager/ProgramLanguage\n\
int8 NONE = -1\n\
\n\
int8 ALL = 0\n\
\n\
# Runnable\n\
int8 PYTHON2 = 1\n\
int8 PYTHON3 = 2\n\
\n\
# Not Runnable\n\
int8 BLOCKLY = 66\n\
\n\
int8 used\n\
";
  }

  static const char* value(const ::niryo_robot_programs_manager::ProgramLanguageList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_programs_manager::ProgramLanguageList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.language_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ProgramLanguageList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_programs_manager::ProgramLanguageList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_programs_manager::ProgramLanguageList_<ContainerAllocator>& v)
  {
    s << indent << "language_list[]" << std::endl;
    for (size_t i = 0; i < v.language_list.size(); ++i)
    {
      s << indent << "  language_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::niryo_robot_programs_manager::ProgramLanguage_<ContainerAllocator> >::stream(s, indent + "    ", v.language_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_PROGRAMS_MANAGER_MESSAGE_PROGRAMLANGUAGELIST_H
