// Generated by gencpp from file tools_interface/PingDxlToolResponse.msg
// DO NOT EDIT!


#ifndef TOOLS_INTERFACE_MESSAGE_PINGDXLTOOLRESPONSE_H
#define TOOLS_INTERFACE_MESSAGE_PINGDXLTOOLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tools_interface/Tool.h>

namespace tools_interface
{
template <class ContainerAllocator>
struct PingDxlToolResponse_
{
  typedef PingDxlToolResponse_<ContainerAllocator> Type;

  PingDxlToolResponse_()
    : state(0)
    , tool()  {
    }
  PingDxlToolResponse_(const ContainerAllocator& _alloc)
    : state(0)
    , tool(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _state_type;
  _state_type state;

   typedef  ::tools_interface::Tool_<ContainerAllocator>  _tool_type;
  _tool_type tool;





  typedef boost::shared_ptr< ::tools_interface::PingDxlToolResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tools_interface::PingDxlToolResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PingDxlToolResponse_

typedef ::tools_interface::PingDxlToolResponse_<std::allocator<void> > PingDxlToolResponse;

typedef boost::shared_ptr< ::tools_interface::PingDxlToolResponse > PingDxlToolResponsePtr;
typedef boost::shared_ptr< ::tools_interface::PingDxlToolResponse const> PingDxlToolResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tools_interface::PingDxlToolResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tools_interface::PingDxlToolResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tools_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'tools_interface': ['/home/niryo/catkin_ws/src/niryo_robot_hardware_stack/tools_interface/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tools_interface::PingDxlToolResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tools_interface::PingDxlToolResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tools_interface::PingDxlToolResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tools_interface::PingDxlToolResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tools_interface::PingDxlToolResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tools_interface::PingDxlToolResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tools_interface::PingDxlToolResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9fae4b0c3f8eadc402f506b70316971e";
  }

  static const char* value(const ::tools_interface::PingDxlToolResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9fae4b0c3f8eadc4ULL;
  static const uint64_t static_value2 = 0x02f506b70316971eULL;
};

template<class ContainerAllocator>
struct DataType< ::tools_interface::PingDxlToolResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tools_interface/PingDxlToolResponse";
  }

  static const char* value(const ::tools_interface::PingDxlToolResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tools_interface::PingDxlToolResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 state\n\
tools_interface/Tool tool\n\
\n\
\n\
================================================================================\n\
MSG: tools_interface/Tool\n\
int8 id\n\
\n\
int8 NO_MOTOR=0\n\
int8 STEPPER=1\n\
int8 XL430=2\n\
int8 XL320=3\n\
int8 XL330=4\n\
int8 XC430=5\n\
int8 FAKE_DXL_MOTOR=6\n\
\n\
int8 motor_type\n\
\n\
\n\
";
  }

  static const char* value(const ::tools_interface::PingDxlToolResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tools_interface::PingDxlToolResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.tool);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PingDxlToolResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tools_interface::PingDxlToolResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tools_interface::PingDxlToolResponse_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.state);
    s << indent << "tool: ";
    s << std::endl;
    Printer< ::tools_interface::Tool_<ContainerAllocator> >::stream(s, indent + "  ", v.tool);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOOLS_INTERFACE_MESSAGE_PINGDXLTOOLRESPONSE_H
