// Generated by gencpp from file tools_interface/Tool.msg
// DO NOT EDIT!


#ifndef TOOLS_INTERFACE_MESSAGE_TOOL_H
#define TOOLS_INTERFACE_MESSAGE_TOOL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tools_interface
{
template <class ContainerAllocator>
struct Tool_
{
  typedef Tool_<ContainerAllocator> Type;

  Tool_()
    : id(0)
    , motor_type(0)  {
    }
  Tool_(const ContainerAllocator& _alloc)
    : id(0)
    , motor_type(0)  {
  (void)_alloc;
    }



   typedef int8_t _id_type;
  _id_type id;

   typedef int8_t _motor_type_type;
  _motor_type_type motor_type;



  enum {
    NO_MOTOR = 0,
    STEPPER = 1,
    XL430 = 2,
    XL320 = 3,
    XL330 = 4,
    XC430 = 5,
    FAKE_DXL_MOTOR = 6,
  };


  typedef boost::shared_ptr< ::tools_interface::Tool_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tools_interface::Tool_<ContainerAllocator> const> ConstPtr;

}; // struct Tool_

typedef ::tools_interface::Tool_<std::allocator<void> > Tool;

typedef boost::shared_ptr< ::tools_interface::Tool > ToolPtr;
typedef boost::shared_ptr< ::tools_interface::Tool const> ToolConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tools_interface::Tool_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tools_interface::Tool_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tools_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'tools_interface': ['/home/niryo/catkin_ws/src/niryo_robot_hardware_stack/tools_interface/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tools_interface::Tool_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tools_interface::Tool_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tools_interface::Tool_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tools_interface::Tool_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tools_interface::Tool_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tools_interface::Tool_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tools_interface::Tool_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d7474e8aafd2648239a8b7699203823";
  }

  static const char* value(const ::tools_interface::Tool_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d7474e8aafd2648ULL;
  static const uint64_t static_value2 = 0x239a8b7699203823ULL;
};

template<class ContainerAllocator>
struct DataType< ::tools_interface::Tool_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tools_interface/Tool";
  }

  static const char* value(const ::tools_interface::Tool_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tools_interface::Tool_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 id\n\
\n\
int8 NO_MOTOR=0\n\
int8 STEPPER=1\n\
int8 XL430=2\n\
int8 XL320=3\n\
int8 XL330=4\n\
int8 XC430=5\n\
int8 FAKE_DXL_MOTOR=6\n\
\n\
int8 motor_type\n\
\n\
\n\
";
  }

  static const char* value(const ::tools_interface::Tool_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tools_interface::Tool_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.motor_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Tool_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tools_interface::Tool_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tools_interface::Tool_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.id);
    s << indent << "motor_type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.motor_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TOOLS_INTERFACE_MESSAGE_TOOL_H
