// Generated by gencpp from file niryo_robot_database/GetAllMetrics.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_DATABASE_MESSAGE_GETALLMETRICS_H
#define NIRYO_ROBOT_DATABASE_MESSAGE_GETALLMETRICS_H

#include <ros/service_traits.h>


#include <niryo_robot_database/GetAllMetricsRequest.h>
#include <niryo_robot_database/GetAllMetricsResponse.h>


namespace niryo_robot_database
{

struct GetAllMetrics
{

typedef GetAllMetricsRequest Request;
typedef GetAllMetricsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAllMetrics
} // namespace niryo_robot_database


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_robot_database::GetAllMetrics > {
  static const char* value()
  {
    return "0ef03c0f3222ccb0494c046fb358e609";
  }

  static const char* value(const ::niryo_robot_database::GetAllMetrics&) { return value(); }
};

template<>
struct DataType< ::niryo_robot_database::GetAllMetrics > {
  static const char* value()
  {
    return "niryo_robot_database/GetAllMetrics";
  }

  static const char* value(const ::niryo_robot_database::GetAllMetrics&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_robot_database::GetAllMetricsRequest> should match 
// service_traits::MD5Sum< ::niryo_robot_database::GetAllMetrics > 
template<>
struct MD5Sum< ::niryo_robot_database::GetAllMetricsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_database::GetAllMetrics >::value();
  }
  static const char* value(const ::niryo_robot_database::GetAllMetricsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_database::GetAllMetricsRequest> should match 
// service_traits::DataType< ::niryo_robot_database::GetAllMetrics > 
template<>
struct DataType< ::niryo_robot_database::GetAllMetricsRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_database::GetAllMetrics >::value();
  }
  static const char* value(const ::niryo_robot_database::GetAllMetricsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_robot_database::GetAllMetricsResponse> should match 
// service_traits::MD5Sum< ::niryo_robot_database::GetAllMetrics > 
template<>
struct MD5Sum< ::niryo_robot_database::GetAllMetricsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_database::GetAllMetrics >::value();
  }
  static const char* value(const ::niryo_robot_database::GetAllMetricsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_database::GetAllMetricsResponse> should match 
// service_traits::DataType< ::niryo_robot_database::GetAllMetrics > 
template<>
struct DataType< ::niryo_robot_database::GetAllMetricsResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_database::GetAllMetrics >::value();
  }
  static const char* value(const ::niryo_robot_database::GetAllMetricsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ROBOT_DATABASE_MESSAGE_GETALLMETRICS_H
