// Generated by gencpp from file niryo_robot_sound/ManageSoundRequest.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_SOUND_MESSAGE_MANAGESOUNDREQUEST_H
#define NIRYO_ROBOT_SOUND_MESSAGE_MANAGESOUNDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_robot_sound
{
template <class ContainerAllocator>
struct ManageSoundRequest_
{
  typedef ManageSoundRequest_<ContainerAllocator> Type;

  ManageSoundRequest_()
    : sound_name()
    , action(0)
    , sound_data()  {
    }
  ManageSoundRequest_(const ContainerAllocator& _alloc)
    : sound_name(_alloc)
    , action(0)
    , sound_data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sound_name_type;
  _sound_name_type sound_name;

   typedef int8_t _action_type;
  _action_type action;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sound_data_type;
  _sound_data_type sound_data;



  enum {
    ADD = 1,
    DELETE = 2,
  };


  typedef boost::shared_ptr< ::niryo_robot_sound::ManageSoundRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_sound::ManageSoundRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ManageSoundRequest_

typedef ::niryo_robot_sound::ManageSoundRequest_<std::allocator<void> > ManageSoundRequest;

typedef boost::shared_ptr< ::niryo_robot_sound::ManageSoundRequest > ManageSoundRequestPtr;
typedef boost::shared_ptr< ::niryo_robot_sound::ManageSoundRequest const> ManageSoundRequestConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_sound::ManageSoundRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_sound::ManageSoundRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace niryo_robot_sound

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'niryo_robot_msgs': ['/home/niryo/catkin_ws/src/niryo_robot_msgs/msg'], 'niryo_robot_sound': ['/home/niryo/catkin_ws/src/niryo_robot_sound/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_sound::ManageSoundRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_sound::ManageSoundRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_sound::ManageSoundRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_sound::ManageSoundRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_sound::ManageSoundRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_sound::ManageSoundRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_sound::ManageSoundRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d206b05f5f80c762821ef2dc0ffb1339";
  }

  static const char* value(const ::niryo_robot_sound::ManageSoundRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd206b05f5f80c762ULL;
  static const uint64_t static_value2 = 0x821ef2dc0ffb1339ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_sound::ManageSoundRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_sound/ManageSoundRequest";
  }

  static const char* value(const ::niryo_robot_sound::ManageSoundRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_sound::ManageSoundRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string sound_name\n\
\n\
int8 ADD = 1\n\
int8 DELETE = 2\n\
int8 action\n\
\n\
\n\
string sound_data\n\
\n\
";
  }

  static const char* value(const ::niryo_robot_sound::ManageSoundRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_sound::ManageSoundRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sound_name);
      stream.next(m.action);
      stream.next(m.sound_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ManageSoundRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_sound::ManageSoundRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_sound::ManageSoundRequest_<ContainerAllocator>& v)
  {
    s << indent << "sound_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sound_name);
    s << indent << "action: ";
    Printer<int8_t>::stream(s, indent + "  ", v.action);
    s << indent << "sound_data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sound_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_SOUND_MESSAGE_MANAGESOUNDREQUEST_H
